routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('exams', 'ExamController');
Route::resource('questions', 'QuestionController');
Route::resource('permissions', 'PermissionController');

app/Exam.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Exam extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/ExamController.php
<?php

namespace App\Http\Controllers;

use App\Exam;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class ExamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {  
       return View('exams.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $s_time = $request['starting_date']; 
        $date = new \DateTime($s_time);
        $s_time= $date->format('Y-m-d H:i:s');
        $e_time = $request['ending_date']; 
        $date2 = new \DateTime($e_time);
        $e_time= $date2->format('Y-m-d H:i:s');


        return Exam::create([
            'name'=>$request['name'],
            'starting_date'=>$s_time,
            'ending_date'=>$e_time,
            'duration'=>$request['duration'],
            
           

        ]);
       
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function show(Exam $exam)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function edit(Exam $exam)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Exam $exam)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function destroy(Exam $exam)
    {
        //
    }
}

resources/views/exams/create.blade.php
<!DOCTYPE html>

<html>
            <head>
                <!-- ... -->
                <script type="text/javascript" src="{{asset('/bower_components/jquery/dist/jquery.min.js')}}"></script>
                <script type="text/javascript" src="{{asset('/bower_components/moment/min/moment.min.js')}}"></script>
                <script type="text/javascript" src="{{asset('/bower_components/bootstrap/js/bootstrap.min.js')}}"></script>
                <script type="text/javascript" src="{{asset('/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js')}}"></script>
                 <link rel="stylesheet" href="{{asset('/bower_components/bootstrap/css/bootstrap.min.css')}}" />
                <link rel="stylesheet" href="{{asset('/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css')}}" />
             </head>

<body>

        

<div class="container">

        <form  method="POST" enctype="multipart/form-data" action="{{ route('exams.store') }}">
                 {{-- <div >
                  <label for="exampleFormControlInput1">Name</label>
                  <input name="name" type="name" class="form-control" id="exampleFormControlInput1" placeholder="name">
                </div> --}}
                <div class="container">
                        <div class="row">
                            <div class='col-sm-6'>

                                    <div >
                                            <label for="exampleFormControlInput1">Name</label>
                                            <input name="name" type="name" class="form-control" id="exampleFormControlInput1" placeholder="name">
                                          </div>

                                <div class="form-group">
                                    <div class='input-group date' id='datetimepicker1'>
                                        <input name="starting_date" type='text' class="form-control" />
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                        <div class='input-group date' id='datetimepicker2'>
                                            <input name="ending_date" type='text' class="form-control" />
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                    </div>
                                    <div >
                                            <label for="exampleFormControlInput2">Duration</label>
                                           <input name="duration" type="text" class="form-control" id="exampleFormControlInput2" placeholder="Duration">
                                       </div>
                            </div>
                            
                         
                        </div>
                    </div>

                {{-- <input type="text" value="2012-05-15 21:05" id="datetimepicker"> --}}
                {{-- <input type="text" value="2012-05-15 21:05" id="datetimepicker">
            <div>
                   
                    <label for="exampleFormControlInput1">Starting time</label>
                  <input name="starting_date" class="date form-control" type="text">
                </div>  
                <div>
                <label for="exampleFormControlInput1">Ending time</label>
                 <input name="ending_date" class="date form-control" type="text">
                </div>     
                        <div >
                             <label for="exampleFormControlInput2">Duration</label>
                            <input name="duration" type="text" class="form-control" id="exampleFormControlInput2" placeholder="Duration">
                        </div> --}}
                <button type="submit" class="btn btn-primary mb-2">Confirm </button>

                <input type="hidden" name="_token" value="{{ Session::token() }}">
              </form>


   
    

</div>





</body>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker();
    });
</script>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker2').datetimepicker();
    });
</script>
</html>